name: $(Date:yyyyMMdd).$(Rev:.r)

container: node:12

steps:
  - script: printenv

# jobs:
#   - job: BuildAndReleaseComponents
#     steps:
#       - script: yarn workspace @astral-frontend/components run build
#       - script: yarn workspace @astral-frontend/components run release

  # - stage: Test
  #   jobs:
  #     - job: TestOnWindows
  #       steps:
  #         - script: echo Testing on Windows!
  #     - job: TestOnLinux
  #       steps:
  #         - script: echo Testing on Linux!
  # - stage: Release
  #   jobs:
  #     - job: Release
  #       steps:
  #         - script: echo Release the code!
